name: PokeOracle CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restaurar dependencias
      run: dotnet restore PokeOracle-Backend/PokeOracle.slnx

    - name: Compilar la solución
      run: dotnet build PokeOracle-Backend/PokeOracle.slnx --no-restore

    - name: Ejecutar Pruebas Unitarias
      run: dotnet test PokeOracle-Backend/PokeOracle.Tests/PokeOracle.Tests.csproj --verbosity normal
